// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sphere.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Sphere represents sphere information
type Sphere struct {
	Job                  string   `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	License              string   `protobuf:"bytes,2,opt,name=license,proto3" json:"license,omitempty"`
	Skill                string   `protobuf:"bytes,3,opt,name=skill,proto3" json:"skill,omitempty"`
	Time                 int32    `protobuf:"varint,4,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Sphere) Reset()         { *m = Sphere{} }
func (m *Sphere) String() string { return proto.CompactTextString(m) }
func (*Sphere) ProtoMessage()    {}
func (*Sphere) Descriptor() ([]byte, []int) {
	return fileDescriptor_969a4ec4166c6933, []int{0}
}

func (m *Sphere) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Sphere.Unmarshal(m, b)
}
func (m *Sphere) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Sphere.Marshal(b, m, deterministic)
}
func (m *Sphere) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sphere.Merge(m, src)
}
func (m *Sphere) XXX_Size() int {
	return xxx_messageInfo_Sphere.Size(m)
}
func (m *Sphere) XXX_DiscardUnknown() {
	xxx_messageInfo_Sphere.DiscardUnknown(m)
}

var xxx_messageInfo_Sphere proto.InternalMessageInfo

func (m *Sphere) GetJob() string {
	if m != nil {
		return m.Job
	}
	return ""
}

func (m *Sphere) GetLicense() string {
	if m != nil {
		return m.License
	}
	return ""
}

func (m *Sphere) GetSkill() string {
	if m != nil {
		return m.Skill
	}
	return ""
}

func (m *Sphere) GetTime() int32 {
	if m != nil {
		return m.Time
	}
	return 0
}

// SphereList a collection of speries
type SphereList struct {
	Items                []*Sphere `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *SphereList) Reset()         { *m = SphereList{} }
func (m *SphereList) String() string { return proto.CompactTextString(m) }
func (*SphereList) ProtoMessage()    {}
func (*SphereList) Descriptor() ([]byte, []int) {
	return fileDescriptor_969a4ec4166c6933, []int{1}
}

func (m *SphereList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SphereList.Unmarshal(m, b)
}
func (m *SphereList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SphereList.Marshal(b, m, deterministic)
}
func (m *SphereList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SphereList.Merge(m, src)
}
func (m *SphereList) XXX_Size() int {
	return xxx_messageInfo_SphereList.Size(m)
}
func (m *SphereList) XXX_DiscardUnknown() {
	xxx_messageInfo_SphereList.DiscardUnknown(m)
}

var xxx_messageInfo_SphereList proto.InternalMessageInfo

func (m *SphereList) GetItems() []*Sphere {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
	proto.RegisterType((*Sphere)(nil), "proto.Sphere")
	proto.RegisterType((*SphereList)(nil), "proto.SphereList")
}

func init() { proto.RegisterFile("sphere.proto", fileDescriptor_969a4ec4166c6933) }

var fileDescriptor_969a4ec4166c6933 = []byte{
	// 152 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0x8e, 0xc1, 0x0a, 0xc2, 0x30,
	0x0c, 0x86, 0xa9, 0x5d, 0x27, 0x46, 0x05, 0x09, 0x1e, 0x72, 0x2c, 0xf3, 0xd2, 0xd3, 0x40, 0x7d,
	0x0d, 0x4f, 0xf5, 0xee, 0x61, 0x12, 0xb0, 0xda, 0xd9, 0xb1, 0xf6, 0xfd, 0x11, 0x53, 0x76, 0xca,
	0xff, 0x7d, 0x09, 0xe1, 0x87, 0x5d, 0x9e, 0x5e, 0x3c, 0x73, 0x3f, 0xcd, 0xa9, 0x24, 0x34, 0x32,
	0xba, 0x07, 0xb4, 0x77, 0xd1, 0x78, 0x00, 0xfd, 0x4e, 0x03, 0x29, 0xab, 0xdc, 0xc6, 0xff, 0x23,
	0x12, 0xac, 0x63, 0x78, 0xf2, 0x37, 0x33, 0xad, 0xc4, 0x2e, 0x88, 0x47, 0x30, 0xf9, 0x13, 0x62,
	0x24, 0x2d, 0xbe, 0x02, 0x22, 0x34, 0x25, 0x8c, 0x4c, 0x8d, 0x55, 0xce, 0x78, 0xc9, 0xdd, 0x19,
	0xa0, 0xfe, 0xbf, 0x85, 0x5c, 0xf0, 0x04, 0x26, 0x14, 0x1e, 0x33, 0x29, 0xab, 0xdd, 0xf6, 0xb2,
	0xaf, 0x5d, 0xfa, 0x7a, 0xe1, 0xeb, 0x6e, 0x68, 0x45, 0x5e, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff,
	0xcc, 0xd0, 0x02, 0xdf, 0xb0, 0x00, 0x00, 0x00,
}
